//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var starsearchVo_ttypes = require('./starsearchVo_types')


var ttypes = require('./soastarsearch_types');
//HELPER FUNCTIONS AND STRUCTURES

StarSearchService_searchStar_args = function(args) {
  this.condition = null;
  if (args) {
    if (args.condition !== undefined && args.condition !== null) {
      this.condition = args.condition;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field condition is unset!');
    }
  }
};
StarSearchService_searchStar_args.prototype = {};
StarSearchService_searchStar_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.condition = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StarSearchService_searchStar_args.prototype.write = function(output) {
  output.writeStructBegin('StarSearchService_searchStar_args');
  if (this.condition !== null && this.condition !== undefined) {
    output.writeFieldBegin('condition', Thrift.Type.STRING, 1);
    output.writeString(this.condition);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StarSearchService_searchStar_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new starsearchVo_ttypes.ResStarSearch(args.success);
    }
  }
};
StarSearchService_searchStar_result.prototype = {};
StarSearchService_searchStar_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new starsearchVo_ttypes.ResStarSearch();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

StarSearchService_searchStar_result.prototype.write = function(output) {
  output.writeStructBegin('StarSearchService_searchStar_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

StarSearchServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
StarSearchServiceClient.prototype = {};
StarSearchServiceClient.prototype.seqid = function() { return this._seqid; }
StarSearchServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
StarSearchServiceClient.prototype.searchStar = function(condition, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_searchStar(condition);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_searchStar(condition);
  }
};

StarSearchServiceClient.prototype.send_searchStar = function(condition) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('searchStar', Thrift.MessageType.CALL, this.seqid());
  var args = new StarSearchService_searchStar_args();
  args.condition = condition;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

StarSearchServiceClient.prototype.recv_searchStar = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new StarSearchService_searchStar_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('searchStar failed: unknown result');
};
StarSearchServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
StarSearchServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

StarSearchServiceProcessor.prototype.process_searchStar = function(seqid, input, output) {
  var args = new StarSearchService_searchStar_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.searchStar.length === 1) {
    Q.fcall(this._handler.searchStar, args.condition)
      .then(function(result) {
        var result = new StarSearchService_searchStar_result({success: result});
        output.writeMessageBegin("searchStar", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("searchStar", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.searchStar(args.condition, function (err, result) {
      if (err == null) {
        var result = new StarSearchService_searchStar_result((err != null ? err : {success: result}));
        output.writeMessageBegin("searchStar", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("searchStar", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

